### ISSUE TITLE
Disable `rake asset:precompile` step if `public/assets` existed

### ISSUE THREAD

**Issue by leomao10** [GoogleCloudPlatform/ruby-docker#153]
We notice when we run `gcloud app deploy`, it will trigger `rake asset:precompile`.

However, we actually follow this document:
https://cloud.google.com/ruby/rails/appengine#deploy_to_app_engine_flexible_environment
to setup our application, so we already run `rake asset:precompile` in our CI.

Also, I noticed `asset:precompile` step actually output following logs during `gcloud app deploy`:
```
Step #1: Step 14/17 : RUN access_cloud_sql --lenient && bundle exec rake assets:precompile || true
Step #1: ---> Running in 13daff15fea9
Step #1: ERROR: Failed to start cloud_sql_proxy
Step #1: 2018/08/08 21:55:33 errors parsing config:
Step #1: googleapi: Error 403: The client is not authorized to make this request., notAuthorized
Step #1: yarn install v1.7.0
Step #1: [1/5] Validating package.json...
Step #1: [2/5] Resolving packages...
Step #1: [3/5] Fetching packages...
Step #1: info fsevents@1.2.3: The platform "linux" is incompatible with this module.
Step #1: info "fsevents@1.2.3" is an optional dependency and failed compatibility check. Excluding it from installation.
Step #1: warning path@0.4.9: The engine "ender" appears to be invalid.
Step #1: [4/5] Linking dependencies...
Step #1: warning "@rails/webpacker > postcss-cssnext@3.1.0" has unmet peer dependency "caniuse-lite@^1.0.30000697".
Step #1: warning " > react2angular@4.0.2" has unmet peer dependency "@types/angular@>=1.5".
Step #1: warning " > react2angular@4.0.2" has unmet peer dependency "@types/prop-types@>=15".
Step #1: warning " > react2angular@4.0.2" has unmet peer dependency "@types/react@>=16".
Step #1: warning " > react2angular@4.0.2" has unmet peer dependency "@types/react-dom@>=16".
Step #1: warning " > webpack-dev-server@2.11.2" has unmet peer dependency "webpack@^2.2.0 || ^3.0.0".
Step #1: warning "webpack-dev-server > webpack-dev-middleware@1.12.2" has unmet peer dependency "webpack@^1.0.0 || ^2.0.0 || ^3.0.0".
Step #1: [5/5] Building fresh packages...
Step #1: error /app/node_modules/phantomjs: Command failed.
Step #1: Exit code: 1
Step #1: Command: node install.js
Step #1: Arguments: 
Step #1: Directory: /app/node_modules/phantomjs
Step #1: Output:
Step #1: PhantomJS not found on PATH
Step #1: Phantom installation failed TypeError: Path must be a string. Received undefined
Step #1: at assertPath (path.js:28:11)
Step #1: at Object.join (path.js:1236:7)
Step #1: at findSuitableTempDirectory (/app/node_modules/phantomjs/install.js:127:30)
Step #1: at /app/node_modules/phantomjs/install.js:476:19
Step #1: at nextTickCallback (/app/node_modules/kew/kew.js:47:28)
Step #1: at _combinedTickCallback (internal/process/next_tick.js:131:7)
Step #1: at process._tickCallback (internal/process/next_tick.js:180:9) TypeError: Path must be a string. Received undefined
Step #1: at assertPath (path.js:28:11)
Step #1: at Object.join (path.js:1236:7)
Step #1: at findSuitableTempDirectory (/app/node_modules/phantomjs/install.js:127:30)
Step #1: at /app/node_modules/phantomjs/install.js:476:19
Step #1: at nextTickCallback (/app/node_modules/kew/kew.js:47:28)
Step #1: at _combinedTickCallback (internal/process/next_tick.js:131:7)
Step #1: at process._tickCallback (internal/process/next_tick.js:180:9)
Step #1: info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Step #1: Webpacker is installed 🎉 🍰
Step #1: Using /app/config/webpacker.yml file for setting up webpack paths
Step #1: Compiling…
Step #1: Compiled all packs in /app/public/packs
```
So I don't really think the step is working 😂 

Base on the reasons above, I was wondering if it is possible that we can somehow disable `rake asset:precompile` or if it can automatically disable it when `public/assets` existed(as an indicator for asset:precompile ran already)

**Comment by leomao10** [comment]
as mentioned in #147, can skip `rake assets:precompile` in `gcloud app deploy` by adding following in app.yaml:

```
runtime_config:
  build: []
```

Also, looks like `cloud_sql_proxy` issue get fixed now, and there is no problem to run `rake assets:precompile` in `gcloud app deploy`, so closing this issue now
