### ISSUE TITLE
Standard Env: Could not find nokogiri-1.10.4 in any of the sources

### ISSUE THREAD

**Issue by mtomov** [GoogleCloudPlatform/ruby-docker#186]
Suddenly from today on deploy I started getting this error.

```yaml
runtime: ruby25
service: web
entrypoint: bin/rails server
instance_class: F4
automatic_scaling:
  max_instances: 2
  max_idle_instances: 2
  target_cpu_utilization: 0.8

handlers:
  - url: /assets
    static_dir: public/assets
    secure: always

...

  - url: /.*
    script: auto
    secure: always
```

```
2019-12-11 18:05:14 web[20191211t175830]  /opt/ruby/lib/ruby/gems/2.5.0/gems/bundler-2.0.2/lib/bundler/spec_set.rb:87:in `block in materialize': Could not find nokogiri-1.10.4 in any of the sources (Bundler::GemNotFound)
2019-12-11 18:05:14 web[20191211t175830]        from /opt/ruby/lib/ruby/gems/2.5.0/gems/bundler-2.0.2/lib/bundler/spec_set.rb:81:in `map!'
2019-12-11 18:05:14 web[20191211t175830]        from /opt/ruby/lib/ruby/gems/2.5.0/gems/bundler-2.0.2/lib/bundler/spec_set.rb:81:in `materialize'
2019-12-11 18:05:14 web[20191211t175830]        from /opt/ruby/lib/ruby/gems/2.5.0/gems/bundler-2.0.2/lib/bundler/definition.rb:170:in `specs'
2019-12-11 18:05:14 web[20191211t175830]        from /opt/ruby/lib/ruby/gems/2.5.0/gems/bundler-2.0.2/lib/bundler/definition.rb:237:in `specs_for'
2019-12-11 18:05:14 web[20191211t175830]        from /opt/ruby/lib/ruby/gems/2.5.0/gems/bundler-2.0.2/lib/bundler/definition.rb:226:in `requested_specs'
2019-12-11 18:05:14 web[20191211t175830]        from /opt/ruby/lib/ruby/gems/2.5.0/gems/bundler-2.0.2/lib/bundler/runtime.rb:108:in `block in definition_method'
2019-12-11 18:05:14 web[20191211t175830]        from /opt/ruby/lib/ruby/gems/2.5.0/gems/bundler-2.0.2/lib/bundler/runtime.rb:20:in `setup'
2019-12-11 18:05:14 web[20191211t175830]        from /opt/ruby/lib/ruby/gems/2.5.0/gems/bundler-2.0.2/lib/bundler.rb:107:in `setup'
2019-12-11 18:05:14 web[20191211t175830]        from /opt/ruby/lib/ruby/gems/2.5.0/gems/bundler-2.0.2/lib/bundler/setup.rb:20:in `<top (required)>'
2019-12-11 18:05:14 web[20191211t175830]        from /opt/ruby/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
2019-12-11 18:05:14 web[20191211t175830]        from /opt/ruby/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
2019-12-11 18:05:14 web[20191211t175830]        from /srv/config/boot.rb:3:in `<top (required)>'
2019-12-11 18:05:14 web[20191211t175830]        from bin/rails:8:in `require_relative'
2019-12-11 18:05:14 web[20191211t175830]        from bin/rails:8:in `<main>'
```

**Comment by dazuma** [comment]
Is this happening consistently? Try deploying again. (Rubygems has been known to flake occasionally.)

(Also, please note that this repo is specific to the flexible environment, so standard environment questions might not get seen by the correct team.)

**Comment by dazuma** [comment]
It looks like there's a systemic issue. We've seen reports on stackoverflow as well.

There was an App Engine Ruby Runtime (Standard Environment) release in progress today that is likely related, so we're rolling it back. That should fix the immediate issue. I'll post any further updates on https://stackoverflow.com/questions/59292862/sudden-could-not-find-nokogiri-1-10-7-in-any-of-the-sources-error-for-previous

**Comment by mtomov** [comment]
Thanks! Appreciated!
